/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as TeamsIndexImport } from './routes/teams/index'
import { Route as StatsIndexImport } from './routes/stats/index'
import { Route as StandingsIndexImport } from './routes/standings/index'
import { Route as ScheduleIndexImport } from './routes/schedule/index'
import { Route as PlayersIndexImport } from './routes/players/index'
import { Route as EditPlayersIndexImport } from './routes/edit-players/index'
import { Route as DashboardIndexImport } from './routes/dashboard/index'
import { Route as ContactUsIndexImport } from './routes/contact-us/index'
import { Route as TeamsTeamNameImport } from './routes/teams/$teamName'
import { Route as PlayersPlayerIdImport } from './routes/players/$playerId'
import { Route as GamesGameIdImport } from './routes/games/$gameId'
import { Route as EditPlayersGameIdImport } from './routes/edit-players/$gameId'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRoute,
} as any)

const StatsIndexRoute = StatsIndexImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRoute,
} as any)

const StandingsIndexRoute = StandingsIndexImport.update({
  id: '/standings/',
  path: '/standings/',
  getParentRoute: () => rootRoute,
} as any)

const ScheduleIndexRoute = ScheduleIndexImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRoute,
} as any)

const PlayersIndexRoute = PlayersIndexImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRoute,
} as any)

const EditPlayersIndexRoute = EditPlayersIndexImport.update({
  id: '/edit-players/',
  path: '/edit-players/',
  getParentRoute: () => rootRoute,
} as any)

const DashboardIndexRoute = DashboardIndexImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRoute,
} as any)

const ContactUsIndexRoute = ContactUsIndexImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamNameRoute = TeamsTeamNameImport.update({
  id: '/teams/$teamName',
  path: '/teams/$teamName',
  getParentRoute: () => rootRoute,
} as any)

const PlayersPlayerIdRoute = PlayersPlayerIdImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRoute,
} as any)

const GamesGameIdRoute = GamesGameIdImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRoute,
} as any)

const EditPlayersGameIdRoute = EditPlayersGameIdImport.update({
  id: '/edit-players/$gameId',
  path: '/edit-players/$gameId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/edit-players/$gameId': {
      id: '/edit-players/$gameId'
      path: '/edit-players/$gameId'
      fullPath: '/edit-players/$gameId'
      preLoaderRoute: typeof EditPlayersGameIdImport
      parentRoute: typeof rootRoute
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdImport
      parentRoute: typeof rootRoute
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdImport
      parentRoute: typeof rootRoute
    }
    '/teams/$teamName': {
      id: '/teams/$teamName'
      path: '/teams/$teamName'
      fullPath: '/teams/$teamName'
      preLoaderRoute: typeof TeamsTeamNameImport
      parentRoute: typeof rootRoute
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsIndexImport
      parentRoute: typeof rootRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardIndexImport
      parentRoute: typeof rootRoute
    }
    '/edit-players/': {
      id: '/edit-players/'
      path: '/edit-players'
      fullPath: '/edit-players'
      preLoaderRoute: typeof EditPlayersIndexImport
      parentRoute: typeof rootRoute
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersIndexImport
      parentRoute: typeof rootRoute
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleIndexImport
      parentRoute: typeof rootRoute
    }
    '/standings/': {
      id: '/standings/'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit-players/$gameId': typeof EditPlayersGameIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamName': typeof TeamsTeamNameRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/edit-players': typeof EditPlayersIndexRoute
  '/players': typeof PlayersIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/teams': typeof TeamsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit-players/$gameId': typeof EditPlayersGameIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamName': typeof TeamsTeamNameRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/edit-players': typeof EditPlayersIndexRoute
  '/players': typeof PlayersIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/teams': typeof TeamsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/edit-players/$gameId': typeof EditPlayersGameIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamName': typeof TeamsTeamNameRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/edit-players/': typeof EditPlayersIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/standings/': typeof StandingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/edit-players/$gameId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/teams/$teamName'
    | '/contact-us'
    | '/dashboard'
    | '/edit-players'
    | '/players'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/edit-players/$gameId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/teams/$teamName'
    | '/contact-us'
    | '/dashboard'
    | '/edit-players'
    | '/players'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/edit-players/$gameId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/teams/$teamName'
    | '/contact-us/'
    | '/dashboard/'
    | '/edit-players/'
    | '/players/'
    | '/schedule/'
    | '/standings/'
    | '/stats/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  EditPlayersGameIdRoute: typeof EditPlayersGameIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  TeamsTeamNameRoute: typeof TeamsTeamNameRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EditPlayersIndexRoute: typeof EditPlayersIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  StandingsIndexRoute: typeof StandingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  EditPlayersGameIdRoute: EditPlayersGameIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  TeamsTeamNameRoute: TeamsTeamNameRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EditPlayersIndexRoute: EditPlayersIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  StandingsIndexRoute: StandingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/sign-in",
        "/sign-up",
        "/edit-players/$gameId",
        "/games/$gameId",
        "/players/$playerId",
        "/teams/$teamName",
        "/contact-us/",
        "/dashboard/",
        "/edit-players/",
        "/players/",
        "/schedule/",
        "/standings/",
        "/stats/",
        "/teams/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/edit-players/$gameId": {
      "filePath": "edit-players/$gameId.tsx"
    },
    "/games/$gameId": {
      "filePath": "games/$gameId.tsx"
    },
    "/players/$playerId": {
      "filePath": "players/$playerId.tsx"
    },
    "/teams/$teamName": {
      "filePath": "teams/$teamName.tsx"
    },
    "/contact-us/": {
      "filePath": "contact-us/index.tsx"
    },
    "/dashboard/": {
      "filePath": "dashboard/index.tsx"
    },
    "/edit-players/": {
      "filePath": "edit-players/index.tsx"
    },
    "/players/": {
      "filePath": "players/index.tsx"
    },
    "/schedule/": {
      "filePath": "schedule/index.tsx"
    },
    "/standings/": {
      "filePath": "standings/index.tsx"
    },
    "/stats/": {
      "filePath": "stats/index.tsx"
    },
    "/teams/": {
      "filePath": "teams/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
