/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignUpImport } from './routes/sign-up'
import { Route as SignInImport } from './routes/sign-in'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as TeamsIndexImport } from './routes/teams/index'
import { Route as StatsIndexImport } from './routes/stats/index'
import { Route as StandingsIndexImport } from './routes/standings/index'
import { Route as ScheduleIndexImport } from './routes/schedule/index'
import { Route as PlayersIndexImport } from './routes/players/index'
import { Route as GamesIndexImport } from './routes/games/index'
import { Route as ContactUsIndexImport } from './routes/contact-us/index'
import { Route as TeamsTeamNameImport } from './routes/teams/$teamName'

// Create/Update Routes

const SignUpRoute = SignUpImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRoute,
} as any)

const SignInRoute = SignInImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsIndexRoute = TeamsIndexImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => rootRoute,
} as any)

const StatsIndexRoute = StatsIndexImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRoute,
} as any)

const StandingsIndexRoute = StandingsIndexImport.update({
  id: '/standings/',
  path: '/standings/',
  getParentRoute: () => rootRoute,
} as any)

const ScheduleIndexRoute = ScheduleIndexImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRoute,
} as any)

const PlayersIndexRoute = PlayersIndexImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRoute,
} as any)

const GamesIndexRoute = GamesIndexImport.update({
  id: '/games/',
  path: '/games/',
  getParentRoute: () => rootRoute,
} as any)

const ContactUsIndexRoute = ContactUsIndexImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRoute,
} as any)

const TeamsTeamNameRoute = TeamsTeamNameImport.update({
  id: '/teams/$teamName',
  path: '/teams/$teamName',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInImport
      parentRoute: typeof rootRoute
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpImport
      parentRoute: typeof rootRoute
    }
    '/teams/$teamName': {
      id: '/teams/$teamName'
      path: '/teams/$teamName'
      fullPath: '/teams/$teamName'
      preLoaderRoute: typeof TeamsTeamNameImport
      parentRoute: typeof rootRoute
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsIndexImport
      parentRoute: typeof rootRoute
    }
    '/games/': {
      id: '/games/'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesIndexImport
      parentRoute: typeof rootRoute
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersIndexImport
      parentRoute: typeof rootRoute
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleIndexImport
      parentRoute: typeof rootRoute
    }
    '/standings/': {
      id: '/standings/'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsIndexImport
      parentRoute: typeof rootRoute
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexImport
      parentRoute: typeof rootRoute
    }
    '/teams/': {
      id: '/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof TeamsIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/teams/$teamName': typeof TeamsTeamNameRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/games': typeof GamesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/teams': typeof TeamsIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/teams/$teamName': typeof TeamsTeamNameRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/games': typeof GamesIndexRoute
  '/players': typeof PlayersIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
  '/teams': typeof TeamsIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/teams/$teamName': typeof TeamsTeamNameRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/games/': typeof GamesIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/standings/': typeof StandingsIndexRoute
  '/stats/': typeof StatsIndexRoute
  '/teams/': typeof TeamsIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/teams/$teamName'
    | '/contact-us'
    | '/games'
    | '/players'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/teams/$teamName'
    | '/contact-us'
    | '/games'
    | '/players'
    | '/schedule'
    | '/standings'
    | '/stats'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/sign-in'
    | '/sign-up'
    | '/teams/$teamName'
    | '/contact-us/'
    | '/games/'
    | '/players/'
    | '/schedule/'
    | '/standings/'
    | '/stats/'
    | '/teams/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TeamsTeamNameRoute: typeof TeamsTeamNameRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  GamesIndexRoute: typeof GamesIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  StandingsIndexRoute: typeof StandingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
  TeamsIndexRoute: typeof TeamsIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TeamsTeamNameRoute: TeamsTeamNameRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  GamesIndexRoute: GamesIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  StandingsIndexRoute: StandingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
  TeamsIndexRoute: TeamsIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/sign-in",
        "/sign-up",
        "/teams/$teamName",
        "/contact-us/",
        "/games/",
        "/players/",
        "/schedule/",
        "/standings/",
        "/stats/",
        "/teams/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/sign-in": {
      "filePath": "sign-in.tsx"
    },
    "/sign-up": {
      "filePath": "sign-up.tsx"
    },
    "/teams/$teamName": {
      "filePath": "teams/$teamName.tsx"
    },
    "/contact-us/": {
      "filePath": "contact-us/index.tsx"
    },
    "/games/": {
      "filePath": "games/index.tsx"
    },
    "/players/": {
      "filePath": "players/index.tsx"
    },
    "/schedule/": {
      "filePath": "schedule/index.tsx"
    },
    "/standings/": {
      "filePath": "standings/index.tsx"
    },
    "/stats/": {
      "filePath": "stats/index.tsx"
    },
    "/teams/": {
      "filePath": "teams/index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
