/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as UnauthenticatedRouteImport } from './routes/unauthenticated'
import { Route as TitleSponsor3RouteImport } from './routes/title-sponsor-3'
import { Route as TitleSponsor2RouteImport } from './routes/title-sponsor-2'
import { Route as TitleSponsor1RouteImport } from './routes/title-sponsor-1'
import { Route as SignUpRouteImport } from './routes/sign-up'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as StatsIndexRouteImport } from './routes/stats/index'
import { Route as StandingsIndexRouteImport } from './routes/standings/index'
import { Route as ScheduleIndexRouteImport } from './routes/schedule/index'
import { Route as PlayersIndexRouteImport } from './routes/players/index'
import { Route as OrganizersIndexRouteImport } from './routes/organizers/index'
import { Route as EditTeamsIndexRouteImport } from './routes/edit-teams/index'
import { Route as EditGamesIndexRouteImport } from './routes/edit-games/index'
import { Route as ContactUsIndexRouteImport } from './routes/contact-us/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as TeamsTeamIdRouteImport } from './routes/teams/$teamId'
import { Route as PlayersPlayerIdRouteImport } from './routes/players/$playerId'
import { Route as GamesGameIdRouteImport } from './routes/games/$gameId'
import { Route as EditTeamsTeamIdRouteImport } from './routes/edit-teams/$teamId'
import { Route as EditGamesGameIdRouteImport } from './routes/edit-games/$gameId'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const UnauthenticatedRoute = UnauthenticatedRouteImport.update({
  id: '/unauthenticated',
  path: '/unauthenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSponsor3Route = TitleSponsor3RouteImport.update({
  id: '/title-sponsor-3',
  path: '/title-sponsor-3',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSponsor2Route = TitleSponsor2RouteImport.update({
  id: '/title-sponsor-2',
  path: '/title-sponsor-2',
  getParentRoute: () => rootRouteImport,
} as any)
const TitleSponsor1Route = TitleSponsor1RouteImport.update({
  id: '/title-sponsor-1',
  path: '/title-sponsor-1',
  getParentRoute: () => rootRouteImport,
} as any)
const SignUpRoute = SignUpRouteImport.update({
  id: '/sign-up',
  path: '/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const StatsIndexRoute = StatsIndexRouteImport.update({
  id: '/stats/',
  path: '/stats/',
  getParentRoute: () => rootRouteImport,
} as any)
const StandingsIndexRoute = StandingsIndexRouteImport.update({
  id: '/standings/',
  path: '/standings/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScheduleIndexRoute = ScheduleIndexRouteImport.update({
  id: '/schedule/',
  path: '/schedule/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersIndexRoute = PlayersIndexRouteImport.update({
  id: '/players/',
  path: '/players/',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizersIndexRoute = OrganizersIndexRouteImport.update({
  id: '/organizers/',
  path: '/organizers/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTeamsIndexRoute = EditTeamsIndexRouteImport.update({
  id: '/edit-teams/',
  path: '/edit-teams/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditGamesIndexRoute = EditGamesIndexRouteImport.update({
  id: '/edit-games/',
  path: '/edit-games/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactUsIndexRoute = ContactUsIndexRouteImport.update({
  id: '/contact-us/',
  path: '/contact-us/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamsTeamIdRoute = TeamsTeamIdRouteImport.update({
  id: '/teams/$teamId',
  path: '/teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayersPlayerIdRoute = PlayersPlayerIdRouteImport.update({
  id: '/players/$playerId',
  path: '/players/$playerId',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesGameIdRoute = GamesGameIdRouteImport.update({
  id: '/games/$gameId',
  path: '/games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditTeamsTeamIdRoute = EditTeamsTeamIdRouteImport.update({
  id: '/edit-teams/$teamId',
  path: '/edit-teams/$teamId',
  getParentRoute: () => rootRouteImport,
} as any)
const EditGamesGameIdRoute = EditGamesGameIdRouteImport.update({
  id: '/edit-games/$gameId',
  path: '/edit-games/$gameId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/title-sponsor-1': typeof TitleSponsor1Route
  '/title-sponsor-2': typeof TitleSponsor2Route
  '/title-sponsor-3': typeof TitleSponsor3Route
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/edit-games/$gameId': typeof EditGamesGameIdRoute
  '/edit-teams/$teamId': typeof EditTeamsTeamIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin': typeof AdminIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/edit-games': typeof EditGamesIndexRoute
  '/edit-teams': typeof EditTeamsIndexRoute
  '/organizers': typeof OrganizersIndexRoute
  '/players': typeof PlayersIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/title-sponsor-1': typeof TitleSponsor1Route
  '/title-sponsor-2': typeof TitleSponsor2Route
  '/title-sponsor-3': typeof TitleSponsor3Route
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/edit-games/$gameId': typeof EditGamesGameIdRoute
  '/edit-teams/$teamId': typeof EditTeamsTeamIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin': typeof AdminIndexRoute
  '/contact-us': typeof ContactUsIndexRoute
  '/edit-games': typeof EditGamesIndexRoute
  '/edit-teams': typeof EditTeamsIndexRoute
  '/organizers': typeof OrganizersIndexRoute
  '/players': typeof PlayersIndexRoute
  '/schedule': typeof ScheduleIndexRoute
  '/standings': typeof StandingsIndexRoute
  '/stats': typeof StatsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/profile': typeof ProfileRoute
  '/sign-in': typeof SignInRoute
  '/sign-up': typeof SignUpRoute
  '/title-sponsor-1': typeof TitleSponsor1Route
  '/title-sponsor-2': typeof TitleSponsor2Route
  '/title-sponsor-3': typeof TitleSponsor3Route
  '/unauthenticated': typeof UnauthenticatedRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/edit-games/$gameId': typeof EditGamesGameIdRoute
  '/edit-teams/$teamId': typeof EditTeamsTeamIdRoute
  '/games/$gameId': typeof GamesGameIdRoute
  '/players/$playerId': typeof PlayersPlayerIdRoute
  '/teams/$teamId': typeof TeamsTeamIdRoute
  '/admin/': typeof AdminIndexRoute
  '/contact-us/': typeof ContactUsIndexRoute
  '/edit-games/': typeof EditGamesIndexRoute
  '/edit-teams/': typeof EditTeamsIndexRoute
  '/organizers/': typeof OrganizersIndexRoute
  '/players/': typeof PlayersIndexRoute
  '/schedule/': typeof ScheduleIndexRoute
  '/standings/': typeof StandingsIndexRoute
  '/stats/': typeof StatsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/title-sponsor-1'
    | '/title-sponsor-2'
    | '/title-sponsor-3'
    | '/unauthenticated'
    | '/unauthorized'
    | '/edit-games/$gameId'
    | '/edit-teams/$teamId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/admin'
    | '/contact-us'
    | '/edit-games'
    | '/edit-teams'
    | '/organizers'
    | '/players'
    | '/schedule'
    | '/standings'
    | '/stats'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/title-sponsor-1'
    | '/title-sponsor-2'
    | '/title-sponsor-3'
    | '/unauthenticated'
    | '/unauthorized'
    | '/edit-games/$gameId'
    | '/edit-teams/$teamId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/admin'
    | '/contact-us'
    | '/edit-games'
    | '/edit-teams'
    | '/organizers'
    | '/players'
    | '/schedule'
    | '/standings'
    | '/stats'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/profile'
    | '/sign-in'
    | '/sign-up'
    | '/title-sponsor-1'
    | '/title-sponsor-2'
    | '/title-sponsor-3'
    | '/unauthenticated'
    | '/unauthorized'
    | '/edit-games/$gameId'
    | '/edit-teams/$teamId'
    | '/games/$gameId'
    | '/players/$playerId'
    | '/teams/$teamId'
    | '/admin/'
    | '/contact-us/'
    | '/edit-games/'
    | '/edit-teams/'
    | '/organizers/'
    | '/players/'
    | '/schedule/'
    | '/standings/'
    | '/stats/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ProfileRoute: typeof ProfileRoute
  SignInRoute: typeof SignInRoute
  SignUpRoute: typeof SignUpRoute
  TitleSponsor1Route: typeof TitleSponsor1Route
  TitleSponsor2Route: typeof TitleSponsor2Route
  TitleSponsor3Route: typeof TitleSponsor3Route
  UnauthenticatedRoute: typeof UnauthenticatedRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
  EditGamesGameIdRoute: typeof EditGamesGameIdRoute
  EditTeamsTeamIdRoute: typeof EditTeamsTeamIdRoute
  GamesGameIdRoute: typeof GamesGameIdRoute
  PlayersPlayerIdRoute: typeof PlayersPlayerIdRoute
  TeamsTeamIdRoute: typeof TeamsTeamIdRoute
  AdminIndexRoute: typeof AdminIndexRoute
  ContactUsIndexRoute: typeof ContactUsIndexRoute
  EditGamesIndexRoute: typeof EditGamesIndexRoute
  EditTeamsIndexRoute: typeof EditTeamsIndexRoute
  OrganizersIndexRoute: typeof OrganizersIndexRoute
  PlayersIndexRoute: typeof PlayersIndexRoute
  ScheduleIndexRoute: typeof ScheduleIndexRoute
  StandingsIndexRoute: typeof StandingsIndexRoute
  StatsIndexRoute: typeof StatsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/unauthenticated': {
      id: '/unauthenticated'
      path: '/unauthenticated'
      fullPath: '/unauthenticated'
      preLoaderRoute: typeof UnauthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title-sponsor-3': {
      id: '/title-sponsor-3'
      path: '/title-sponsor-3'
      fullPath: '/title-sponsor-3'
      preLoaderRoute: typeof TitleSponsor3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title-sponsor-2': {
      id: '/title-sponsor-2'
      path: '/title-sponsor-2'
      fullPath: '/title-sponsor-2'
      preLoaderRoute: typeof TitleSponsor2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/title-sponsor-1': {
      id: '/title-sponsor-1'
      path: '/title-sponsor-1'
      fullPath: '/title-sponsor-1'
      preLoaderRoute: typeof TitleSponsor1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-up': {
      id: '/sign-up'
      path: '/sign-up'
      fullPath: '/sign-up'
      preLoaderRoute: typeof SignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stats/': {
      id: '/stats/'
      path: '/stats'
      fullPath: '/stats'
      preLoaderRoute: typeof StatsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/standings/': {
      id: '/standings/'
      path: '/standings'
      fullPath: '/standings'
      preLoaderRoute: typeof StandingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schedule/': {
      id: '/schedule/'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/': {
      id: '/players/'
      path: '/players'
      fullPath: '/players'
      preLoaderRoute: typeof PlayersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizers/': {
      id: '/organizers/'
      path: '/organizers'
      fullPath: '/organizers'
      preLoaderRoute: typeof OrganizersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-teams/': {
      id: '/edit-teams/'
      path: '/edit-teams'
      fullPath: '/edit-teams'
      preLoaderRoute: typeof EditTeamsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-games/': {
      id: '/edit-games/'
      path: '/edit-games'
      fullPath: '/edit-games'
      preLoaderRoute: typeof EditGamesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact-us/': {
      id: '/contact-us/'
      path: '/contact-us'
      fullPath: '/contact-us'
      preLoaderRoute: typeof ContactUsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teams/$teamId': {
      id: '/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof TeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/players/$playerId': {
      id: '/players/$playerId'
      path: '/players/$playerId'
      fullPath: '/players/$playerId'
      preLoaderRoute: typeof PlayersPlayerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games/$gameId': {
      id: '/games/$gameId'
      path: '/games/$gameId'
      fullPath: '/games/$gameId'
      preLoaderRoute: typeof GamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-teams/$teamId': {
      id: '/edit-teams/$teamId'
      path: '/edit-teams/$teamId'
      fullPath: '/edit-teams/$teamId'
      preLoaderRoute: typeof EditTeamsTeamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-games/$gameId': {
      id: '/edit-games/$gameId'
      path: '/edit-games/$gameId'
      fullPath: '/edit-games/$gameId'
      preLoaderRoute: typeof EditGamesGameIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ProfileRoute: ProfileRoute,
  SignInRoute: SignInRoute,
  SignUpRoute: SignUpRoute,
  TitleSponsor1Route: TitleSponsor1Route,
  TitleSponsor2Route: TitleSponsor2Route,
  TitleSponsor3Route: TitleSponsor3Route,
  UnauthenticatedRoute: UnauthenticatedRoute,
  UnauthorizedRoute: UnauthorizedRoute,
  EditGamesGameIdRoute: EditGamesGameIdRoute,
  EditTeamsTeamIdRoute: EditTeamsTeamIdRoute,
  GamesGameIdRoute: GamesGameIdRoute,
  PlayersPlayerIdRoute: PlayersPlayerIdRoute,
  TeamsTeamIdRoute: TeamsTeamIdRoute,
  AdminIndexRoute: AdminIndexRoute,
  ContactUsIndexRoute: ContactUsIndexRoute,
  EditGamesIndexRoute: EditGamesIndexRoute,
  EditTeamsIndexRoute: EditTeamsIndexRoute,
  OrganizersIndexRoute: OrganizersIndexRoute,
  PlayersIndexRoute: PlayersIndexRoute,
  ScheduleIndexRoute: ScheduleIndexRoute,
  StandingsIndexRoute: StandingsIndexRoute,
  StatsIndexRoute: StatsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
